package mainpackage;

public enum Errors {
	//isin
	ERROR_ISIN_LOCALLY_NOT_FOUND,
	ERROR_ISIN_GLOBALLY_NOT_FOUND,
	ERROR_ISIN_INVALID_LENGTH,
	//quotation
	ERROR_QUOTATION_NULL,
	//exceptions
	ERROR_PARSE_EXCEPTION,
	ERROR_PARSING_XML_EXCEPTION,
	ERROR_PARSING_HTML_EXCEPTION,
	ERROR_ARRAY_INDEXOUTOFBOUND_EXCEPTION,
	ERROR_STRING_INDEXOUTOFBOUND_EXCEPTION,
	ERROR_IO_EXCEPTION,
	ERROR_SAX_EXCEPTION,
	ERROR_PARSING_DATE_EXCEPTION,
	//numbers
	ERROR_NAN,
	
	//responses
	ERROR_NONE,
	ERROR_OK,
	//database
	ERROR_DATABASE_CONNECTION,
	ERROR_INVALID_SQL,
	ERROR_EMPTY_TABLE,
	ERROR_INVALID_TABLE,
	//json
	ERROR_JSON_PACKING
}