package mainpackage;

public enum Errors {
	//isin
	ERROR_ISIN_LOCALLY_NOT_FOUND,
	WARNING_NOT_FOUND_IN_PREFERRED_SITE,
	ERROR_ISIN_GLOBALLY_NOT_FOUND,
	ERROR_ISIN_INVALID_LENGTH,
	ERROR_NULL_YAHOO_CODE,
	ERROR_YAHOO_CODE_SEARCH,
	//requests
	ERROR_INVALID_JSON,
	ERROR_INVALID_REQUEST,
	ERROR_INVALID_REQUEST_TYPE,
	ERROR_INVALID_ISIN,
	//responses
	ERROR_NONE,
	ERROR_OK,
	//database
	ERROR_DATABASE_CONNECTION,
	//history
	ERROR_NULL_HISTORY_LIST
}